services:
  db:
    image: mysql
    ports:
      - "3366:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  countries:
    depends_on: [db]
    image: aleksandar3811/countries:v1
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root

